<FORM NAME="zeitraum" ACTION="zeigeKosten.php" METHOD="POST">
von <SELECT NAME="vTag">
	<OPTION>1</OPTION>
	<OPTION>2</OPTION>
	<OPTION>3</OPTION>
	<OPTION>4</OPTION>
	<OPTION>5</OPTION>
	<OPTION>6</OPTION>
	<OPTION>7</OPTION>
	<OPTION>8</OPTION>
	<OPTION>9</OPTION>
	<OPTION>10</OPTION>
	<OPTION>11</OPTION>
	<OPTION>12</OPTION>
	<OPTION>13</OPTION>
	<OPTION>14</OPTION>
	<OPTION>15</OPTION>
	<OPTION>16</OPTION>
	<OPTION>17</OPTION>
	<OPTION>18</OPTION>
	<OPTION>19</OPTION>
	<OPTION>20</OPTION>
	<OPTION>21</OPTION>
	<OPTION>22</OPTION>
	<OPTION>23</OPTION>
	<OPTION>24</OPTION>
	<OPTION>25</OPTION>
	<OPTION>26</OPTION>
	<OPTION>27</OPTION>
	<OPTION>28</OPTION>
	<OPTION>29</OPTION>
	<OPTION>30</OPTION>
	<OPTION>31</OPTION>
  </SELECT>
  <SELECT NAME="vMonat">
	<OPTION VALUE="1">Januar</OPTION>
	<OPTION VALUE="2">Februar</OPTION>
	<OPTION VALUE="3">M&auml;rz</OPTION>
	<OPTION VALUE="4">April</OPTION>
	<OPTION VALUE="5">Mai</OPTION>
	<OPTION VALUE="6">Juni</OPTION>
	<OPTION VALUE="7">Juli</OPTION>
	<OPTION VALUE="8">August</OPTION>
	<OPTION VALUE="9">September</OPTION>
	<OPTION VALUE="10">Oktober</OPTION>
	<OPTION VALUE="11">November</OPTION>
	<OPTION VALUE="12">Dezember</OPTION>
  </SELECT>
  <SELECT NAME="vJahr">
	<OPTION>2003</OPTION>
	<OPTION>2004</OPTION>
	<OPTION>2005</OPTION>
	<OPTION>2006</OPTION>
	<OPTION>2007</OPTION>
  </SELECT>
 bis <SELECT NAME="bTag">
	<OPTION>1</OPTION>
	<OPTION>2</OPTION>
	<OPTION>3</OPTION>
	<OPTION>4</OPTION>
	<OPTION>5</OPTION>
	<OPTION>6</OPTION>
	<OPTION>7</OPTION>
	<OPTION>8</OPTION>
	<OPTION>9</OPTION>
	<OPTION>10</OPTION>
	<OPTION>11</OPTION>
	<OPTION>12</OPTION>
	<OPTION>13</OPTION>
	<OPTION>14</OPTION>
	<OPTION>15</OPTION>
	<OPTION>16</OPTION>
	<OPTION>17</OPTION>
	<OPTION>18</OPTION>
	<OPTION>19</OPTION>
	<OPTION>20</OPTION>
	<OPTION>21</OPTION>
	<OPTION>22</OPTION>
	<OPTION>23</OPTION>
	<OPTION>24</OPTION>
	<OPTION>25</OPTION>
	<OPTION>26</OPTION>
	<OPTION>27</OPTION>
	<OPTION>28</OPTION>
	<OPTION>29</OPTION>
	<OPTION>30</OPTION>
	<OPTION>31</OPTION>
  </SELECT>
  <SELECT NAME="bMonat">
	<OPTION VALUE="1">Januar</OPTION>
	<OPTION VALUE="2">Februar</OPTION>
	<OPTION VALUE="3">M&auml;rz</OPTION>
	<OPTION VALUE="4">April</OPTION>
	<OPTION VALUE="5">Mai</OPTION>
	<OPTION VALUE="6">Juni</OPTION>
	<OPTION VALUE="7">Juli</OPTION>
	<OPTION VALUE="8">August</OPTION>
	<OPTION VALUE="9">September</OPTION>
	<OPTION VALUE="10">Oktober</OPTION>
	<OPTION VALUE="11">November</OPTION>
	<OPTION VALUE="12">Dezember</OPTION>
  </SELECT>
  <SELECT NAME="bJahr">
	<OPTION>2003</OPTION>
	<OPTION>2004</OPTION>
	<OPTION>2005</OPTION>
	<OPTION>2006</OPTION>
	<OPTION>2007</OPTION>
  </SELECT>
<INPUT TYPE="SUBMIT" NAME="Anzeige" VALUE="zeigen">
</FORM>
