# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mail-Ezmlm-Gpg
version:      0.1
version_from: Gpg.pm
installdirs:  site
requires:
    Mail::Ezmlm:                   0.05

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
